version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - MSSQL_SA_PASSWORD=VooTreeVeeVuu@123
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    networks:
      - app-network

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - sqlserver
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
