version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - MSSQL_SA_PASSWORD=VooTreeVeeVuu@123
#      - MSSQL_SA_PASSWORD=${SQL_SERVER_PASSWORD}
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    networks:
      - app-network

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:sqlserver://sqlserver:1433;encrypt=true;trustServerCertificate=true;databaseName=DATN_VooTreeVeeVuu
#      SPRING_DATASOURCE_USERNAME: ${SQL_SERVER_USER}
#      SPRING_DATASOURCE_PASSWORD: ${SQL_SERVER_PASSWORD}
    depends_on:
      - sqlserver
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
